### ISSUE TITLE
request code

### ISSUE THREAD

**Issue by ezmess** [mertyg/post-hoc-cbm#1]
I really like your post-hoc CBM paper. Can you share your code?

**Comment by mertyg** [comment]
Hi @ezmess  ,
Thank you for the kind words! Apologies for the delay.

As the work is still under review a full release involving all components may come later, but I'll do my best to release a good enough codebase in the next few days.

**Comment by mertyg** [comment]
Hey @ezmess  , we just released most existing functionality. Closing this issue now, feel free to open one / e-mail me if you need other things!
