### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by SiyuanYan1** [mertyg/post-hoc-cbm#2]
Thanks for your great work! Do you have any plan to release the code of posthoc CBM?

**Comment by mertyg** [comment]
Hi @redlessme  ,
Thank you for the kind words! Apologies for the delay.

As the work is still under review a full release involving all components may come later, but I'll do my best to release a good enough codebase in the next few days.

**Comment by mertyg** [comment]
Hey @redlessme , we just released most existing functionality. Closing this issue now, feel free to open one / e-mail me if you need other things!
