### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by alceubissoto** [mertyg/post-hoc-cbm#3]
Hi! Congratulations for the amazing work! 
I would really appreciate if the code was available. Thank you!

**Comment by mertyg** [comment]
Hi @alceubissoto ,
Thank you for the kind words! Apologies for the delay. 

As the work is still under review a full release involving all components may come later, but I'll do my best to release a good enough codebase in the next few days.

**Comment by alceubissoto** [comment]
Thank you @mertyg !
